tap "cjbassi/ytop"
tap "extrawurst/tap"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "jason0x43/homebrew-neovim-nightly"
tap "koekeishiya/formulae"
# tap "github/gh"
# tap "wix/brew"
cask_args appdir: "/Applications"

brew "asdf"
brew "bat"
brew "curl"
brew "exa"
#brew "fzf"
#brew "gh"
brew "git"
brew "grep"
#brew "htop"
brew "jq"
brew "mas"
#brew "ncdu"
brew "skhd"
brew "starship"
brew "stow"
brew "tealdeer"
brew "tmux"
brew "yabai"
#brew "ytop"
#brew "zoxide"
brew "zsh"
brew "zsh-autosuggestions"
brew "svn"

cask "alacritty"
cask "alfred"
cask "font-roboto"
cask "font-roboto-mono"
cask "google-chrome"
cask "google-japanese-ime"
cask "hammerspoon"
cask "insomnia"
cask "neovim-nightly"
cask "slack"
cask "visual-studio-code"
cask "zoom"

#mas "Simple Recorder-Voice Recorder", id: 989175722
