[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'dense-analysis/ale'
# 明示的に要求したもの以外をALEに実行しない
# 左端のシンボルカラムを表示したままにする
# ファイル保存時に整形実行
# エラーのシンボル
# 警告のシンボル
hook_add = '''
let g:ale_linters_explicit = 1
let g:ale_sign_column_always = 1
let g:ale_fix_on_save = 1
let g:ale_sign_error = 'E'
let g:ale_sign_warning = 'W'
'''

[[plugins]]
repo = 'frazrepo/vim-rainbow'
hook_add = 'let g:rainbow_active = 1'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'ruanyl/vim-gh-line'

[[plugins]]
repo = 'taohexxx/lightline-buffer'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'tpope/vim-commentary'

# LF
[[plugins]]
repo = 'ptzz/lf.vim'

[[plugins]]
repo = 'voldikss/vim-floaterm'

# FZF
[[plugins]]
repo = 'junegunn/fzf'

[[plugins]]
repo = 'junegunn/fzf.vim'

# Language Specific
[[plugins]]
repo = 'yuezk/vim-js'

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'

[[plugins]]
repo = 'cespare/vim-toml'

# Color Scheme
[[plugins]]
repo = 'drewtempelmeyer/palenight.vim'

[[plugins]]
repo = 'haishanh/night-owl.vim'

[[plugins]]
repo = 'kaicataldo/material.vim'
rev  = 'main'
hook_add = '''
colorscheme material
let g:material_terminal_italics = 1
let g:material_theme_style = 'default'
'''