[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'dense-analysis/ale'
# 明示的に要求したもの以外をALEに実行しない
# 左端のシンボルカラムを表示したままにする
# ファイル保存時に整形実行
# エラーのシンボル
# 警告のシンボル
hook_add = '''
let g:ale_linters_explicit = 1
let g:ale_sign_column_always = 1
let g:ale_fix_on_save = 1
let g:ale_sign_error = 'E'
let g:ale_sign_warning = 'W'
'''

[[plugins]]
repo = 'frazrepo/vim-rainbow'
hook_add = 'let g:rainbow_active = 1'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['lightline-buffer', 'material.vim']
hook_add = '''
set hidden " 保存されていないファイルがあるときでも別のファイルを開くことが出来る
set showtabline=2 " タブを表示する

let g:lightline = {
    \ 'colorscheme': 'material_vim',
    \ 'component_function': {
    \   'bufferinfo': 'lightline#buffer#bufferinfo',
    \   'filename': 'FilenameForLightline',
    \ },
    \ 'tabline': {
    \   'left': [ [ 'bufferinfo' ],
    \             [ 'separator' ],
    \             [ 'bufferbefore', 'buffercurrent', 'bufferafter' ], ],
    \   'right': [ [ 'close' ], ],
    \ },
    \ 'component_expand': {
    \   'buffercurrent': 'lightline#buffer#buffercurrent',
    \   'bufferbefore': 'lightline#buffer#bufferbefore',
    \   'bufferafter': 'lightline#buffer#bufferafter',
    \ },
    \ 'component_type': {
    \   'buffercurrent': 'tabsel',
    \   'bufferbefore': 'raw',
    \   'bufferafter': 'raw',
    \ },
    \ 'component': {
    \   'separator': '',
    \ },
    \ }

let g:lightline_buffer_logo = ' '
let g:lightline_buffer_readonly_icon = ''
let g:lightline_buffer_modified_icon = '✭'
let g:lightline_buffer_git_icon = ' '
let g:lightline_buffer_ellipsis_icon = '..'
let g:lightline_buffer_expand_left_icon = '◀ '
let g:lightline_buffer_expand_right_icon = ' ▶'
let g:lightline_buffer_active_buffer_left_icon = ''
let g:lightline_buffer_active_buffer_right_icon = ''
let g:lightline_buffer_separator_icon = '  '

let g:lightline_buffer_enable_devicons = 1 " enable devicons, only support utf-8
let g:lightline_buffer_show_bufnr = 1 " lightline-buffer function settings
let g:lightline_buffer_fname_mod = ':t' " :help filename-modifiers
let g:lightline_buffer_excludes = ['vimfiler'] " hide buffer list
let g:lightline_buffer_maxflen = 30 " max file name length
let g:lightline_buffer_maxfextlen = 3 " max file extension length
let g:lightline_buffer_minflen = 16 " min file name length
let g:lightline_buffer_minfextlen = 3 " min file extension length
let g:lightline_buffer_reservelen = 20 " reserve length for other component (e.g. info, close)

function! FilenameForLightline()
    return expand('%')
endfunction
'''

[[plugins]]
repo = 'taohexxx/lightline-buffer'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'ruanyl/vim-gh-line'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'tpope/vim-commentary'

# LF
[[plugins]]
repo = 'ptzz/lf.vim'
build_on = '''
let g:lf_map_keys = 0
'''

[[plugins]]
repo = 'voldikss/vim-floaterm'

# FZF
[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'
hook_add = '''
let g:fzf_buffers_jump = 1
let g:fzf_layout = { 'down': '40%' }
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \   'rg --line-number --column --no-heading --hidden --color=always --smart-case --glob ''!**/.git/*'' --glob ''!**/node_modules/*'' '.shellescape(<q-args>), 0,
    \   fzf#vim#with_preview('right:50%:wrap'))
'''

# Language Specific
[[plugins]]
repo = 'yuezk/vim-js'

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'

[[plugins]]
repo = 'cespare/vim-toml'

# Color Scheme
[[plugins]]
repo = 'kaicataldo/material.vim'
rev  = 'main'
hook_source = '''
let g:material_terminal_italics = 1
let g:material_theme_style = 'default'
colorscheme material
'''